using Nop.Core;

namespace Nop.Plugin.Misc.SellerMarketing.Domain;

/// <summary>
/// Represents a backup archive record generated by the system for a seller
/// </summary>
public partial class SellerBackupRecord : BaseEntity
{
    /// <summary>
    /// Gets or sets the vendor identifier
    /// </summary>
    public int VendorId { get; set; }

    /// <summary>
    /// Gets or sets the file name
    /// </summary>
    public string FileName { get; set; }

    /// <summary>
    /// Gets or sets the relative or absolute internal server file path
    /// </summary>
    public string FilePath { get; set; }

    /// <summary>
    /// Gets or sets the cryptographic SHA-256 hash of the complete backup archive
    /// </summary>
    public string FileHashSha256 { get; set; }

    /// <summary>
    /// Gets or sets the HMAC-SHA256 signature sealing the manifest and payload
    /// </summary>
    public string HmacSignature { get; set; }

    /// <summary>
    /// Gets or sets the comma-separated list of entities included in the backup
    /// </summary>
    public string IncludedEntities { get; set; }

    /// <summary>
    /// Gets or sets the size of the backup file in bytes
    /// </summary>
    public long FileSizeBytes { get; set; }

    /// <summary>
    /// Gets or sets the creation date in UTC
    /// </summary>
    public DateTime CreatedOnUtc { get; set; }
}
